# Schema for the configuration files of the generator_entity_pdf module.
generator_entity_pdf.settings:
  type: config_object
  label: 'generator_entity_pdf settings'
  mapping:
    orientation:
      type: string
      label: 'Orientation'
    unit:
      type: string
      label: 'Unit'
    format:
      type: string
      label: 'Format'
    header:
      type: config_object
      label: 'Display header'
      mapping:
        show:
          type: boolean
          label: 'Show'
        class:
          type: string
          label: 'Class'
    footer:
      type: config_object
      label: 'Display footer'
      mapping:
        show:
          type: boolean
          label: 'Show'
        class:
          type: string
          label: 'Class'
